### ISSUE TITLE
Provide reset props when needed

### ISSUE THREAD

**Issue by farzinfadamin** [suweya/react-verification-code-input#10]
I need to reset all fields in some situations. For instance when the code has been entered is not correct. Right now I need to re-render the whole component which sucks.

Hope see an update very soon @suweya

**Comment by suweiyang** [comment]
Hi @farzinfadamin 
you can use React ref to call inner func
like this

```
this._CodeInputRef = React.createRef();

<CodeInput ref={this._CodeInputRef} />

this._CodeInputRef && this._CodeInputRef.current.__clearvalues__();
```

**Comment by suweya** [comment]
Hi @farzinfadamin 
you can use React ref to call inner func
like this

```
this._CodeInputRef = React.createRef();

<CodeInput ref={this._CodeInputRef} />

this._CodeInputRef && this._CodeInputRef.current.__clearvalues__();
```

**Comment by Developer-Raman** [comment]
@suweya  __clearvalues__() should update in documentation for quick reference.
