### ISSUE TITLE
Can not copy and paste code into input fields

### ISSUE THREAD

**Issue by cmwint** [suweya/react-verification-code-input#18]
After commit #https://github.com/suweya/react-verification-code-input/commit/573174590bc556aac3a217ef1d4c6c1af2594053 I am no longer able to copy and paste the code into the input fields. It is due to the input pattern missing an asterisk at the end. This is happening across chrome, firefox and safari browsers. What was the reason why this was removed? I'm happy to submit a PR for this to add it back in.

I am specifically talking about this line: https://github.com/suweya/react-verification-code-input/blob/master/src/index.js#L216

**Comment by suweya** [comment]
Sorry, It could be a mistake. Fixed in v1.2.3. You can upgrade @cmwint

**Comment by cmwint** [comment]
Just tested the upgrade version, and it works great. Thank you, @suweya!
