### ISSUE TITLE
View config not found for name input. Make sure to start component names with a capital letter.

### ISSUE THREAD

**Issue by maks112v** [suweya/react-verification-code-input#26]
Invariant Violation: View config not found for name input. Make sure to start component names with a capital letter.

This error is located at:
    in input (created by ReactCodeInput)
    in div (created by ReactCodeInput)
    in div (created by ReactCodeInput)
    in ReactCodeInput (at VerifyNumber.js:14)
    in RCTView (at VerifyNumber.js:12)
    in RCTSafeAreaView (at SafeAreaView.js:55)
    in SafeAreaView (at VerifyNumber.js:11)
    in RCTView (at KeyboardAvoidingView.js:207)
    in KeyboardAvoidingView (at VerifyNumber.js:9)
    in VerifyNumber (at SceneView.tsx:98)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:89)
    in EnsureSingleNavigator (at SceneView.tsx:88)
    in SceneView (at useDescriptors.tsx:125)
    in RCTView (at CardContainer.tsx:199)
    in RCTView (at CardContainer.tsx:198)
    in RCTView (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:526)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.tsx:508)
    in PanGestureHandler (at GestureHandler.native.tsx:13)
    in PanGestureHandler (at Card.tsx:502)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.tsx:498)
    in RCTView (at Card.tsx:492)
    in Card (at CardContainer.tsx:164)
    in CardContainer (at CardStack.tsx:497)
    in RCTView (at Screens.tsx:70)
    in MaybeScreen (at CardStack.tsx:490)
    in RCTView (at Screens.tsx:48)
    in MaybeScreenContainer (at CardStack.tsx:388)
    in CardStack (at StackView.tsx:433)
    in KeyboardManager (at StackView.tsx:431)
    in RNCSafeAreaView (at src/index.tsx:28)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at StackView.tsx:428)
    in RCTView (at StackView.tsx:427)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at App.js:51)
    in RootStackRouter (at App.js:112)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:288)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:66)
    in ThemeProvider (at NavigationContainer.tsx:65)
    in ForwardRef(NavigationContainer) (at App.js:111)
    in AuthWrapper (at App.js:110)
    in App (at withExpoRoot.js:21)
    in RootErrorBoundary (at withExpoRoot.js:20)
    in ExpoRoot (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in DevAppContainer (at AppContainer.js:115)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

exports.get
    ReactNativeViewConfigRegistry.js:93:8
renderRoot
    [native code]:0
runRootCallback
    [native code]:0
dispatchAction
    [native code]:0
setValue
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:176656:15
nn
    auth.js:372:150
tryCallOne
    core.js:37:14
setImmediate$argument_0
    core.js:123:25
callImmediates
    [native code]:0
flushedQueue
    [native code]:0
callFunctionReturnFlushedQueue
    [native code]:0

**Comment by suweya** [comment]
It is not supported React Native
