### ISSUE TITLE
styles are difficult to override 

### ISSUE THREAD

**Issue by vitordino** [suweya/react-verification-code-input#3]
hey @suweya, first of all congrats on this nice component (:

i‘ve just noticed that as the styles are imported by default, and they have some `!important`s on it, so its kinda difficult styling over this component..

and although the default style is pretty nice, some would want to adapt it to it's theme. i think there’s some possible work arounds to fix this:

1. **breaking**: stop importing the style (people using would have to import it aside the component, as [`react-slick`](https://github.com/akiran/react-slick) and other packages does)

2. **non-breaking**: rewrite the css so there’s no usage of `!important`s

---

there are advantages on each approach (eg.: build-size vs default styling) that you can opt into, but i think this issue deserves an action, on either direction, to improve usability

**Comment by vitordino** [comment]
I’ve tested it from here (although not exhaustively) and found out that the `!important`s aren’t needed for the styles to work properly

I’ll open an PR to enable further discussion on this topic

**Comment by suweya** [comment]
Thanks @vitordino

**Comment by dminkovsky** [comment]
Would be really nice to stop importing the css by default.

**Comment by suweya** [comment]
@dminkovsky  you suggest separation css file?

**Comment by dminkovsky** [comment]
I think so... otherwise maybe allow to specify selectors in such a way that it's easy to override without `!important`. Right now I don't see a way to specify selectors that are more specific than the built in ones.
