### ISSUE TITLE
移动端点击某个已选的输入框会弹出「复制粘贴全选」选项。

### ISSUE THREAD

**Issue by ZhaoTim** [suweya/react-verification-code-input#33]
你好，我最近在做关于验证码输入框的需求，看到您做的很棒！只是我在实施的过程中发现，一旦我有一个输出框输出错误，我点击输入错误的输入框，想重新更改数字时，总是会弹出一个全选复制的选项，我看了源码发现应该是每次点击时，做了一个全选的操作，所以才会有这样的问题，所以想问一下，这种问题是否有解决方案呢？
（找了好久都没找到解决方案。。。快疯了）

**Comment by suweya** [comment]
是想去掉 https://github.com/suweya/react-verification-code-input/blob/master/src/index.js#L125 ？
