### ISSUE TITLE
Clear values in TypeScript

### ISSUE THREAD

**Issue by Ampa1R** [suweya/react-verification-code-input#39]
Hi! Thanks for awesome package!
I am trying to clear values but having problems with types. Can you show me how to do it right?

**Comment by suweya** [comment]
https://github.com/suweya/react-verification-code-input/issues/15
this maybe help you

**Comment by Ampa1R** [comment]
Thank you for quick response
I saw this issue, but I'm interested in how to do it with typescript. Looks like there are not enough types in .d.ts file

**Comment by suweya** [comment]
oh i know 
It is not define in https://github.com/suweya/react-verification-code-input/blob/master/src/index.d.ts

**Comment by Ampa1R** [comment]
Could you please fix it?

**Comment by suweya** [comment]
will do

**Comment by suweya** [comment]
pls try `1.2.7`

**Comment by nir-c2c** [comment]
@suweya , I wonder if something broke with 1.2.7. typescript is complaining on the index.d.ts file which were the changes you put in for 1.2.7. I reverted back to 1.2.6 and i can compile my code now.

**Comment by Ampa1R** [comment]
Yeah, looks like it's broken now
@suweya

**Comment by suweya** [comment]
@nir-c2c @Ampa1R there was a mistake, please try `1.2.8`, thanks.

**Comment by nir-c2c** [comment]
@suweya it looks like it is working now!
Thanks for the fast fix
